using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <inheritdoc />
    public partial class FixPostgresIdentity : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("ALTER TABLE \"DespesasFixas\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
                migrationBuilder.Sql("ALTER TABLE \"PagamentosDespesasFixas\" ALTER COLUMN \"Id\" ADD GENERATED BY DEFAULT AS IDENTITY;");
                
                migrationBuilder.Sql("SELECT setval(pg_get_serial_sequence('\"DespesasFixas\"', 'Id'), coalesce(max(\"Id\"), 1), max(\"Id\") IS NOT null) FROM \"DespesasFixas\";");
                migrationBuilder.Sql("SELECT setval(pg_get_serial_sequence('\"PagamentosDespesasFixas\"', 'Id'), coalesce(max(\"Id\"), 1), max(\"Id\") IS NOT null) FROM \"PagamentosDespesasFixas\";");
            }
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            if (migrationBuilder.ActiveProvider == "Npgsql.EntityFrameworkCore.PostgreSQL")
            {
                migrationBuilder.Sql("ALTER TABLE \"DespesasFixas\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
                migrationBuilder.Sql("ALTER TABLE \"PagamentosDespesasFixas\" ALTER COLUMN \"Id\" DROP IDENTITY IF EXISTS;");
            }
        }
    }
}
